//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoccerManager.SoccerWebservice {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SoccerWebservice.SoccerManager_WebserviceSoap")]
    public interface SoccerManager_WebserviceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string HelloWorld();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddSpelerGegevens", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool AddSpelerGegevens(string voornaam, string naam, string team);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddTeamGegevens", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool AddTeamGegevens(string naam, string verantwoordelijke, string straat_nr, string postcode, string plaats, string telefoon, string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddTeamNaam", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool AddTeamNaam(string naam);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddNieuweWedstrijd", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool AddNieuweWedstrijd(string team1, string team2, string terrein, string poule, string datum, string uur, string scheidsrechter, string opmerking);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectTeamNaam", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SelectTeamNaam();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectSpelerGegevens", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SelectSpelerGegevens();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SelectTeamNaamPerPoule", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet SelectTeamNaamPerPoule(string poule);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SoccerManager_WebserviceSoapChannel : SoccerManager.SoccerWebservice.SoccerManager_WebserviceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SoccerManager_WebserviceSoapClient : System.ServiceModel.ClientBase<SoccerManager.SoccerWebservice.SoccerManager_WebserviceSoap>, SoccerManager.SoccerWebservice.SoccerManager_WebserviceSoap {
        
        public SoccerManager_WebserviceSoapClient() {
        }
        
        public SoccerManager_WebserviceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SoccerManager_WebserviceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SoccerManager_WebserviceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SoccerManager_WebserviceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string HelloWorld() {
            return base.Channel.HelloWorld();
        }
        
        public bool AddSpelerGegevens(string voornaam, string naam, string team) {
            return base.Channel.AddSpelerGegevens(voornaam, naam, team);
        }
        
        public bool AddTeamGegevens(string naam, string verantwoordelijke, string straat_nr, string postcode, string plaats, string telefoon, string email) {
            return base.Channel.AddTeamGegevens(naam, verantwoordelijke, straat_nr, postcode, plaats, telefoon, email);
        }
        
        public bool AddTeamNaam(string naam) {
            return base.Channel.AddTeamNaam(naam);
        }
        
        public bool AddNieuweWedstrijd(string team1, string team2, string terrein, string poule, string datum, string uur, string scheidsrechter, string opmerking) {
            return base.Channel.AddNieuweWedstrijd(team1, team2, terrein, poule, datum, uur, scheidsrechter, opmerking);
        }
        
        public System.Data.DataSet SelectTeamNaam() {
            return base.Channel.SelectTeamNaam();
        }
        
        public System.Data.DataSet SelectSpelerGegevens() {
            return base.Channel.SelectSpelerGegevens();
        }
        
        public System.Data.DataSet SelectTeamNaamPerPoule(string poule) {
            return base.Channel.SelectTeamNaamPerPoule(poule);
        }
    }
}
