//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoccerManager.SoccerWebservice {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SoccerWebservice.SoccerManager_WebserviceSoap")]
    public interface SoccerManager_WebserviceSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        SoccerManager.SoccerWebservice.HelloWorldResponse HelloWorld(SoccerManager.SoccerWebservice.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name voornaam from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddSpelerGegevens", ReplyAction="*")]
        SoccerManager.SoccerWebservice.AddSpelerGegevensResponse AddSpelerGegevens(SoccerManager.SoccerWebservice.AddSpelerGegevensRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public SoccerManager.SoccerWebservice.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(SoccerManager.SoccerWebservice.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public SoccerManager.SoccerWebservice.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(SoccerManager.SoccerWebservice.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddSpelerGegevensRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddSpelerGegevens", Namespace="http://tempuri.org/", Order=0)]
        public SoccerManager.SoccerWebservice.AddSpelerGegevensRequestBody Body;
        
        public AddSpelerGegevensRequest() {
        }
        
        public AddSpelerGegevensRequest(SoccerManager.SoccerWebservice.AddSpelerGegevensRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddSpelerGegevensRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string voornaam;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string naam;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string team;
        
        public AddSpelerGegevensRequestBody() {
        }
        
        public AddSpelerGegevensRequestBody(string voornaam, string naam, string team) {
            this.voornaam = voornaam;
            this.naam = naam;
            this.team = team;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddSpelerGegevensResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddSpelerGegevensResponse", Namespace="http://tempuri.org/", Order=0)]
        public SoccerManager.SoccerWebservice.AddSpelerGegevensResponseBody Body;
        
        public AddSpelerGegevensResponse() {
        }
        
        public AddSpelerGegevensResponse(SoccerManager.SoccerWebservice.AddSpelerGegevensResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddSpelerGegevensResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AddSpelerGegevensResult;
        
        public AddSpelerGegevensResponseBody() {
        }
        
        public AddSpelerGegevensResponseBody(bool AddSpelerGegevensResult) {
            this.AddSpelerGegevensResult = AddSpelerGegevensResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SoccerManager_WebserviceSoapChannel : SoccerManager.SoccerWebservice.SoccerManager_WebserviceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SoccerManager_WebserviceSoapClient : System.ServiceModel.ClientBase<SoccerManager.SoccerWebservice.SoccerManager_WebserviceSoap>, SoccerManager.SoccerWebservice.SoccerManager_WebserviceSoap {
        
        public SoccerManager_WebserviceSoapClient() {
        }
        
        public SoccerManager_WebserviceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SoccerManager_WebserviceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SoccerManager_WebserviceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SoccerManager_WebserviceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoccerManager.SoccerWebservice.HelloWorldResponse SoccerManager.SoccerWebservice.SoccerManager_WebserviceSoap.HelloWorld(SoccerManager.SoccerWebservice.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            SoccerManager.SoccerWebservice.HelloWorldRequest inValue = new SoccerManager.SoccerWebservice.HelloWorldRequest();
            inValue.Body = new SoccerManager.SoccerWebservice.HelloWorldRequestBody();
            SoccerManager.SoccerWebservice.HelloWorldResponse retVal = ((SoccerManager.SoccerWebservice.SoccerManager_WebserviceSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoccerManager.SoccerWebservice.AddSpelerGegevensResponse SoccerManager.SoccerWebservice.SoccerManager_WebserviceSoap.AddSpelerGegevens(SoccerManager.SoccerWebservice.AddSpelerGegevensRequest request) {
            return base.Channel.AddSpelerGegevens(request);
        }
        
        public bool AddSpelerGegevens(string voornaam, string naam, string team) {
            SoccerManager.SoccerWebservice.AddSpelerGegevensRequest inValue = new SoccerManager.SoccerWebservice.AddSpelerGegevensRequest();
            inValue.Body = new SoccerManager.SoccerWebservice.AddSpelerGegevensRequestBody();
            inValue.Body.voornaam = voornaam;
            inValue.Body.naam = naam;
            inValue.Body.team = team;
            SoccerManager.SoccerWebservice.AddSpelerGegevensResponse retVal = ((SoccerManager.SoccerWebservice.SoccerManager_WebserviceSoap)(this)).AddSpelerGegevens(inValue);
            return retVal.Body.AddSpelerGegevensResult;
        }
    }
}
